Add secret verification

diff --git a/.github/workflows/frontend-ci-cd.yml b/.github/workflows/frontend-ci-cd.yml
--- a/.github/workflows/frontend-ci-cd.yml
+++ b/.github/workflows/frontend-ci-cd.yml
@@ -32,6 +32,13 @@ jobs:
 
       - name: Build
         run: npm run build
+              - name: Verify Secrets
+        run: |
+          if [ -z "${{ secrets.AWS_S3_BUCKET }}" ]; then
+            echo "AWS_S3_BUCKET is missing"
+            exit 1
+          fi
+          echo "AWS_S3_BUCKET exists"
 
       - name: Deploy To S3
         uses: jakejarvis/s3-sync-action@master
